import type { AIModelOption } from './types';

export const STATIC_MODELS: AIModelOption[] = [
  {
    id: 'gemini-3-pro-preview',
    name: 'Gemini 3 Pro',
    description: 'Most capable Gemini model in Sherlock',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'DEEP_RESEARCH',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-3-flash-preview',
    name: 'Gemini 3 Flash',
    description: 'Fast and balanced Gemini default',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'GENERAL',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    description: 'Advanced reasoning profile',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'DEEP_RESEARCH',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: false,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    description: 'Cost-effective Gemini option',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'FAST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: false,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    description: 'High-throughput Gemini option',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: false,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    description: 'OpenAI fast general model',
    provider: 'OPENAI',
    source: 'STATIC',
    recommendedRole: 'FAST',
    capabilities: {
      supportsThinkingBudget: false,
      supportsStructuredOutput: true,
      supportsWebSearch: false,
      supportsToolUse: false,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'claude-3-5-haiku-latest',
    name: 'Claude 3.5 Haiku',
    description: 'Anthropic fast general model',
    provider: 'ANTHROPIC',
    source: 'STATIC',
    recommendedRole: 'FAST',
    capabilities: {
      supportsThinkingBudget: false,
      supportsStructuredOutput: true,
      supportsWebSearch: false,
      supportsToolUse: false,
      runtimeStatus: 'ACTIVE',
    },
  },
];

export const OPENROUTER_SNAPSHOT_MODELS: AIModelOption[] = [
  {
    id: 'openrouter/free',
    name: 'OpenRouter Free Router',
    description: 'Routes to current free models and filters for supported features.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 200000,
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'openrouter/auto',
    name: 'OpenRouter Auto',
    description: 'Lets OpenRouter route across the best available supported models.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'GENERAL',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'openai/gpt-5.4-mini',
    name: 'OpenAI: GPT-5.4 Mini',
    description: 'Balanced frontier-grade OpenRouter option for research and chat.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'GENERAL',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 400000,
    maxCompletionTokens: 128000,
    supportedParameters: [
      'include_reasoning',
      'max_tokens',
      'reasoning',
      'response_format',
      'seed',
      'structured_outputs',
      'tool_choice',
      'tools',
    ],
  },
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Anthropic: Claude Sonnet 4',
    description: 'Strong all-around OpenRouter model for investigation and synthesis.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'DEEP_RESEARCH',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 200000,
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'google/gemini-2.5-flash',
    name: 'Google: Gemini 2.5 Flash',
    description: 'Fast multimodal OpenRouter option with configurable reasoning.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'FAST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 1048576,
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'google/gemini-2.5-flash-lite',
    name: 'Google: Gemini 2.5 Flash Lite',
    description: 'Low-latency OpenRouter workhorse with optional reasoning.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 1048576,
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'qwen/qwen3.6-plus:free',
    name: 'Qwen: Qwen3.6 Plus (free)',
    description: 'High-context free OpenRouter model with reasoning and tool support.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 1000000,
    maxCompletionTokens: 65536,
    supportedParameters: [
      'include_reasoning',
      'max_tokens',
      'presence_penalty',
      'reasoning',
      'response_format',
      'seed',
      'structured_outputs',
      'temperature',
      'tool_choice',
      'tools',
      'top_p',
    ],
  },
];

export const OPENROUTER_QUICK_PICK_IDS = [
  'openrouter/free',
  'openrouter/auto',
  'openai/gpt-5.4-mini',
  'anthropic/claude-sonnet-4',
  'google/gemini-2.5-flash',
  'qwen/qwen3.6-plus:free',
];

export const AI_MODELS: AIModelOption[] = [...STATIC_MODELS, ...OPENROUTER_SNAPSHOT_MODELS];
