import type { AIModelOption } from './types';

export const STATIC_MODELS: AIModelOption[] = [
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro',
    description: 'Latest high-capability Gemini model for deep research and synthesis.',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'DEEP_RESEARCH',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-3-flash-preview',
    name: 'Gemini 3 Flash',
    description: 'Fast and balanced Gemini default.',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'GENERAL',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-3.1-flash-lite-preview',
    name: 'Gemini 3.1 Flash-Lite',
    description: 'Latest low-latency Gemini preview for high-throughput work.',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    description: 'Stable Gemini reasoning model with long context and tool support.',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'DEEP_RESEARCH',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    description: 'Stable Gemini flash model for balanced speed, cost, and grounding.',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'FAST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    description: 'Stable low-latency Gemini option for high-throughput work.',
    provider: 'GEMINI',
    source: 'STATIC',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gpt-5.4',
    name: 'GPT-5.4',
    description: 'OpenAI flagship model for complex reasoning, coding, and analysis.',
    provider: 'OPENAI',
    source: 'STATIC',
    recommendedRole: 'DEEP_RESEARCH',
    capabilities: {
      supportsThinkingBudget: false,
      supportsStructuredOutput: true,
      supportsWebSearch: false,
      supportsToolUse: false,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gpt-5.4-mini',
    name: 'GPT-5.4 Mini',
    description: 'Balanced OpenAI default for general work, coding, and research.',
    provider: 'OPENAI',
    source: 'STATIC',
    recommendedRole: 'GENERAL',
    capabilities: {
      supportsThinkingBudget: false,
      supportsStructuredOutput: true,
      supportsWebSearch: false,
      supportsToolUse: false,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'gpt-5.4-nano',
    name: 'GPT-5.4 Nano',
    description: 'Lowest-cost OpenAI option for short, high-throughput tasks.',
    provider: 'OPENAI',
    source: 'STATIC',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: false,
      supportsStructuredOutput: true,
      supportsWebSearch: false,
      supportsToolUse: false,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    description: 'Anthropic flagship model for the most complex reasoning and coding work.',
    provider: 'ANTHROPIC',
    source: 'STATIC',
    recommendedRole: 'DEEP_RESEARCH',
    capabilities: {
      supportsThinkingBudget: false,
      supportsStructuredOutput: true,
      supportsWebSearch: false,
      supportsToolUse: false,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    description: 'Balanced Anthropic default with strong speed and intelligence.',
    provider: 'ANTHROPIC',
    source: 'STATIC',
    recommendedRole: 'GENERAL',
    capabilities: {
      supportsThinkingBudget: false,
      supportsStructuredOutput: true,
      supportsWebSearch: false,
      supportsToolUse: false,
      runtimeStatus: 'ACTIVE',
    },
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    description: 'Fast Anthropic option with near-frontier intelligence.',
    provider: 'ANTHROPIC',
    source: 'STATIC',
    recommendedRole: 'FAST',
    capabilities: {
      supportsThinkingBudget: false,
      supportsStructuredOutput: true,
      supportsWebSearch: false,
      supportsToolUse: false,
      runtimeStatus: 'ACTIVE',
    },
  },
];

export const OPENROUTER_SNAPSHOT_MODELS: AIModelOption[] = [
  {
    id: 'openrouter/free',
    name: 'OpenRouter Free Router',
    description: 'Routes to current free models and filters for supported features.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 200000,
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'openrouter/auto',
    name: 'OpenRouter Auto',
    description: 'Lets OpenRouter route across the best available supported models.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'GENERAL',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'openai/gpt-5.4-mini',
    name: 'OpenAI: GPT-5.4 Mini',
    description: 'Balanced frontier-grade OpenRouter option for research and chat.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'GENERAL',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 400000,
    maxCompletionTokens: 128000,
    supportedParameters: [
      'include_reasoning',
      'max_tokens',
      'reasoning',
      'response_format',
      'seed',
      'structured_outputs',
      'tool_choice',
      'tools',
    ],
  },
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Anthropic: Claude Sonnet 4',
    description: 'Strong all-around OpenRouter model for investigation and synthesis.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'DEEP_RESEARCH',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 200000,
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'google/gemini-2.5-flash',
    name: 'Google: Gemini 2.5 Flash',
    description: 'Fast multimodal OpenRouter option with configurable reasoning.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'FAST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 1048576,
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'google/gemini-2.5-flash-lite',
    name: 'Google: Gemini 2.5 Flash Lite',
    description: 'Low-latency OpenRouter workhorse with optional reasoning.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 1048576,
    supportedParameters: ['reasoning', 'response_format', 'structured_outputs', 'tools'],
  },
  {
    id: 'qwen/qwen3.6-plus:free',
    name: 'Qwen: Qwen3.6 Plus (free)',
    description: 'High-context free OpenRouter model with reasoning and tool support.',
    provider: 'OPENROUTER',
    source: 'OPENROUTER_SNAPSHOT',
    recommendedRole: 'LOW_COST',
    capabilities: {
      supportsThinkingBudget: true,
      supportsStructuredOutput: true,
      supportsWebSearch: true,
      supportsToolUse: true,
      supportsVision: true,
      runtimeStatus: 'ACTIVE',
    },
    contextLength: 1000000,
    maxCompletionTokens: 65536,
    supportedParameters: [
      'include_reasoning',
      'max_tokens',
      'presence_penalty',
      'reasoning',
      'response_format',
      'seed',
      'structured_outputs',
      'temperature',
      'tool_choice',
      'tools',
      'top_p',
    ],
  },
];

export const OPENROUTER_QUICK_PICK_IDS = [
  'openrouter/free',
  'openrouter/auto',
  'openai/gpt-5.4-mini',
  'anthropic/claude-sonnet-4',
  'google/gemini-2.5-flash',
  'qwen/qwen3.6-plus:free',
];

export const AI_MODELS: AIModelOption[] = [...STATIC_MODELS, ...OPENROUTER_SNAPSHOT_MODELS];
