import type {
  Artifact,
  TimelineEvent,
  TimelineFilters,
  TimelineSnapshot,
  TimelineTrack,
  Workspace,
} from '@/types';
import { buildArtifactFollowUps, getWorkspaceDisplayTitle } from '../../../domain';

const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
};

const TRACK_LABELS: Record<TimelineTrack, string> = {
  SIGNAL: 'Signal',
  RUN: 'Run',
  ARTIFACT: 'Artifact',
  ITEM: 'Item',
  CHAT: 'Chat',
  ENTITY: 'Entity',
};

const normalizeFileToken = (value: string) =>
  value
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

const formatEventTimestamp = (occurredAt: number) =>
  occurredAt > 0 ? new Date(occurredAt).toISOString() : 'UNKNOWN_TIME';

const formatEventLine = (event: TimelineEvent) => {
  const badges = event.badges?.length ? ` [${event.badges.join(', ')}]` : '';
  const summary = event.summary ? ` - ${event.summary}` : '';
  return `${formatEventTimestamp(event.occurredAt)} | ${TRACK_LABELS[event.track]} | ${event.title}${badges}${summary}`;
};

const buildSnapshotFilename = (workspace: Workspace, suffix: string) =>
  `${normalizeFileToken(getWorkspaceDisplayTitle(workspace) || 'WORKSPACE')}_TIMELINE_${suffix}`;

export const buildTimelineSnapshot = (input: {
  workspace: Workspace;
  events: TimelineEvent[];
  filters: TimelineFilters;
  search: string;
  focusedTrack?: TimelineTrack | 'ALL';
  focusedRefId?: string;
  generatedAt?: string;
}): TimelineSnapshot => ({
  workspace: input.workspace,
  events: input.events,
  metadata: {
    generatedAt: input.generatedAt || new Date().toISOString(),
    range: input.filters.range,
    tracks: input.filters.tracks,
    search: input.search,
    focusedTrack: input.focusedTrack,
    focusedRefId: input.focusedRefId,
  },
});

export const buildTimelineSnapshotMarkdown = (snapshot: TimelineSnapshot): string => {
  const lines = snapshot.events.map((event) => `- ${formatEventLine(event)}`);
  const tracks = snapshot.metadata.tracks.length > 0 ? snapshot.metadata.tracks.join(', ') : 'ALL';

  return [
    `# Timeline Snapshot: ${getWorkspaceDisplayTitle(snapshot.workspace)}`,
    '',
    `Generated: ${snapshot.metadata.generatedAt}`,
    `Range: ${snapshot.metadata.range}`,
    `Tracks: ${tracks}`,
    `Search: ${snapshot.metadata.search || 'None'}`,
    `Focused Track: ${snapshot.metadata.focusedTrack || 'ALL'}`,
    `Focused Reference: ${snapshot.metadata.focusedRefId || 'None'}`,
    `Events: ${snapshot.events.length}`,
    '',
    '## Chronology',
    ...(lines.length > 0 ? lines : ['- No events matched this snapshot.']),
    '',
    `*Generated by Sherlock on ${new Date(snapshot.metadata.generatedAt).toLocaleString()}*`,
  ].join('\n');
};

export const downloadTimelineSnapshotJson = (snapshot: TimelineSnapshot) => {
  downloadFile(
    JSON.stringify(snapshot, null, 2),
    `${buildSnapshotFilename(snapshot.workspace, 'SNAPSHOT')}.json`,
    'application/json'
  );
};

export const downloadTimelineSnapshotMarkdown = (snapshot: TimelineSnapshot) => {
  downloadFile(
    buildTimelineSnapshotMarkdown(snapshot),
    `${buildSnapshotFilename(snapshot.workspace, 'SNAPSHOT')}.md`,
    'text/markdown'
  );
};

export const buildTimelineSnapshotArtifact = (snapshot: TimelineSnapshot): Artifact => {
  const timelineItems = snapshot.events.map(formatEventLine);
  const trackBreakdown = snapshot.metadata.tracks.map(
    (track) => `${TRACK_LABELS[track]} track included`
  );

  return {
    workspaceId: snapshot.workspace.id,
    topic: `${getWorkspaceDisplayTitle(snapshot.workspace)} Timeline Snapshot`,
    dateStr: new Date(snapshot.metadata.generatedAt).toLocaleDateString(),
    createdAt: Date.parse(snapshot.metadata.generatedAt) || Date.now(),
    summary:
      snapshot.events.length > 0
        ? `${snapshot.events.length} timeline events captured for ${getWorkspaceDisplayTitle(snapshot.workspace)}.`
        : `Timeline snapshot saved before any events were visible for ${getWorkspaceDisplayTitle(snapshot.workspace)}.`,
    agendas: [
      `${snapshot.events.length} visible chronology events`,
      `Range: ${snapshot.metadata.range}`,
      `Search: ${snapshot.metadata.search || 'None'}`,
      ...(trackBreakdown.length > 0 ? trackBreakdown : ['All primary tracks included']),
    ],
    leads: snapshot.events
      .slice(0, 5)
      .map((event) => `${TRACK_LABELS[event.track]}: ${event.title}`),
    sections: [
      {
        id: `timeline-summary-${snapshot.workspace.id}`,
        kind: 'EXECUTIVE_SUMMARY',
        title: 'Timeline Snapshot Summary',
        content: [
          `Workspace: ${getWorkspaceDisplayTitle(snapshot.workspace)}`,
          `Generated: ${snapshot.metadata.generatedAt}`,
          `Visible events: ${snapshot.events.length}`,
          `Focused track: ${snapshot.metadata.focusedTrack || 'ALL'}`,
          `Focused reference: ${snapshot.metadata.focusedRefId || 'None'}`,
        ].join('\n'),
      },
      {
        id: `timeline-track-summary-${snapshot.workspace.id}`,
        kind: 'KEY_FINDINGS',
        title: 'Timeline Filters',
        items: [
          `Range: ${snapshot.metadata.range}`,
          `Tracks: ${snapshot.metadata.tracks.join(', ') || 'ALL'}`,
          `Search query: ${snapshot.metadata.search || 'None'}`,
        ],
        order: 1,
      },
      {
        id: `timeline-events-${snapshot.workspace.id}`,
        kind: 'TIMELINE',
        title: 'Chronology',
        items: timelineItems,
        order: 2,
      },
    ],
    followUps: buildArtifactFollowUps({
      followUps: snapshot.events.slice(0, 3).map((event) => event.title),
    }),
    artifactType: 'TIMELINE',
    entities: [],
    sources: [],
    rawText: JSON.stringify(snapshot, null, 2),
    packId: snapshot.workspace.packId,
    purposeId: snapshot.workspace.purposeId,
    labelProfileId: snapshot.workspace.labelProfileId,
    metadata: {
      source: 'TIMELINE',
      snapshotGeneratedAt: snapshot.metadata.generatedAt,
      visibleEventCount: snapshot.events.length,
      focusedTrack: snapshot.metadata.focusedTrack || 'ALL',
      focusedRefId: snapshot.metadata.focusedRefId,
    },
    config: {
      scopeId: snapshot.workspace.scopeId,
      packId: snapshot.workspace.packId,
      purposeId: snapshot.workspace.purposeId,
      artifactType: 'TIMELINE',
      labelProfileId: snapshot.workspace.labelProfileId,
    },
  };
};
