export const INSPECTOR_ACTION_SHORT_LABELS = {
  add: 'Add',
  board: 'Board',
  chat: 'Chat',
  entity: 'Entity',
  files: 'Files',
  google: 'Google',
  item: 'Item',
  link: 'Link',
  network: 'Network',
  note: 'Note',
  open: 'Open',
  parent: 'Parent',
  previous: 'Previous',
  signal: 'Signal',
  run: 'Run',
  session: 'Session',
  source: 'Source',
  summary: 'Summary',
  timeline: 'Timeline',
} as const;
